name: 'Run Tests With Wheel Installed'
description: 'Run Unit Tests And Examples With Wheel Installed'

inputs:
  os:
    description: "operating system"
    required: true

runs:
  using: "composite"
  steps:
    # TODO: build wheel first, then run the test
    - name: Run Unittests And Examples
      shell: bash
      run: |
        python -m unittest discover -v tests
        uv pip install --system -r examples/applications/requirements_applications.txt
        for example in "./examples"/*.py; do
          echo "Running $example"
          PYTHONPATH=. python $example
        done
        for example in "./examples/applications"/*.py; do
          echo "Running $example"
          PYTHONPATH=. python $example
        done
