name: 'Setup Environment'
description: 'Setup Environment'

inputs:
  os:
    description: "operating system"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: "3.10"

    - name: Update System (Linux)
      shell: bash
      if: inputs.os == 'Linux'
      run: |
        sudo apt update -y
        sudo apt install -y build-essential tzdata cmake clang curl pkg-config g++-14
        sudo chmod 755 ./scripts/download_install_libraries.sh
        sudo chmod 755 ./scripts/build.sh

    - name: Install Python Base Packages
      shell: bash
      run: |
        pip install uv
        uv pip install --system --upgrade pip

    - name: Cache Library Install
      if: inputs.os == 'Linux'
      id: cache-library
      uses: actions/cache@v4
      with:
        path: |
          capnproto-*
        key: ${{ inputs.os }}-${{ hashFiles('scripts/download_install_libraries.*') }}

    - name: Download/Compile Libraries (Linux)
      shell: bash
      if: (inputs.os == 'Linux') && (steps.cache-library.outputs.cache-hit != 'true')
      run: |
        sudo ./scripts/download_install_libraries.sh capnp compile

    - name: Download/Compile Libraries (Windows)
      shell: pwsh
      if: (inputs.os == 'Windows') && (steps.cache-boost-windows.outputs.cache-hit != 'true')
      run: |
        ./scripts/download_install_libraries.ps1 capnp compile

    - name: Install Libraries (Linux)
      shell: bash
      if: inputs.os == 'Linux'
      run: |
        sudo ./scripts/download_install_libraries.sh capnp install

    - name: Install Libraries (Windows)
      shell: pwsh
      if: inputs.os == 'Windows'
      run: |
        ./scripts/download_install_libraries.ps1 capnp install
