scheduler_address = "tcp://127.0.0.1:6378"
num_of_workers = 4
worker_names = ""
per_worker_capabilities = ""
worker_io_threads = 1
per_worker_task_queue_size = 1000
heartbeat_interval_seconds = 2
task_timeout_seconds = 0
death_timeout_seconds = 300
garbage_collect_interval_seconds = 30
trim_memory_threshold_bytes = 1073741824
hard_processor_suspend = false
logging_level = "INFO"
logging_paths = ["/dev/stdout"]