scheduler_address = "tcp://127.0.0.1:6378"
storage_address = "tcp://127.0.0.1:6379"
monitor_address = "tcp://127.0.0.1:6380"
adapter_webhook_url = "http://127.0.0.1:8080"
protected = true
allocate_policy = "even"
event_loop = "builtin"
io_threads = 1
max_number_of_tasks_waiting = -1
client_timeout_seconds = 60
worker_timeout_seconds = 60
object_retention_seconds = 60
load_balance_seconds = 1
load_balance_trigger_times = 2
logging_level = "INFO"
logging_paths = ["/dev/stdout"]
# config_file = "logging.conf"